<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>E_Commerce_System_API.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.4" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.11" />
    <PackageReference Include="SQLitePCLRaw.core" Version="2.1.11" />
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.11" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\E-Commerce_System-API.Application\E-Commerce_System-API.Application.csproj" />
    <ProjectReference Include="..\E-Commerce_System-API.Domain\E-Commerce_System-API.Domain.csproj" />
  </ItemGroup>

</Project>
